version: '3'
services:
  www:
    #build: .
    image: node:11
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    tty: true
  broker:
    hostname: rabbit_node_1
    image: rabbitmq:3
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit:/var/lib/rabbitmq
volumes:
  persistent: # for db
  rabbit:
    driver: local